name: tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore tests/DayZ.MaskEditor.Core.Tests/DayZ.MaskEditor.Core.Tests.csproj

      - name: Test
        run: >
          dotnet test tests/DayZ.MaskEditor.Core.Tests/DayZ.MaskEditor.Core.Tests.csproj
          --configuration Release
          --no-restore
